------------------------------------------------------------------------

---
title: "Metadados - Bases de Dados: ApuraSUS, BPS e SIOPS"
Subtitle: "**Departamento de Economia e Desenvolvimento em Saúde - DESID**"
format: html
lang: pt  # Linguagem em português
date: "'r format(Sys.Date())'" # Data do relatório - fica atualizando
date-format: short  # para formato dd/mm/aaaa
toc: true  # para aparecer um índice no lado direito do relatório - false não aparece

editor: visual
---

::: callout-note
1.  O Departamento de Economia e Desenvolvimento em Saúde - Desid é responsável por análises econômicas em saúde e ferramentas importantes para o planejamento dos profissionais que fazem a gestão do SUS, como o Sistema de Informações de Orçamentos Públicos em Saúde (SIOPS), o Banco de Preços em Saúde (BPS), o Catálogo de Materiais (CATMAT) e o Programa Nacional de Gestão de Custos (PNGC).

2.  Com a reestruturação do Ministério da Saúde, o Desid também passou a contar com uma nova área de atuação, e incorporou ao seu rol de serviços a Economia Política da Saúde. Esta área é responsável por estudos como os de conjuntura e seus impactos na saúde da população, ou levantamentos da participação da saúde no Produto Interno Bruto (PIB) brasileiro e dos benefícios da oferta de assistência para a economia do país.
:::

|                                            |
|--------------------------------------------|
| title: "Catálogo de Metadados"             |
| author: "Ministério da Saúde - MS"         |
| format: html                               |
| editor: visual                             |
| "Bloco G - Edifício SEDE - CEP: 70058-900" |
| "e-Mail: desid\@saude.gov.br"              |
| editor_options:                            |
| chunk_output_type: inline                  |

------------------------------------------------------------------------

::: callout-important
-   Os Metadados estão relacionados aos três Sistema do DESID.🧐

-   O Glossário está relacionado às palavras e aos termos acerca dos metadados.🧐

-   As Referência aprofundam a pesquisa sobre os metadados e auxiliam no entendimento.🧐
:::

::: panel-tabset
## Metadado

| Base de Dados (Sistema) | Sistema de Apuração e Gestão de Custos do SUS - ApuraSUS |
|----|----|
| Dado | Tabela AU_RLCRITERIORATEIOUNIDCENTCUS |
| Descrição | DBAPURASUS.RL_CRITERIORATEIO_UNIDCENTCUST: Tabela de |
| Relaçăo dos Critério de Rateios para a Unidade de Saúde |  |
| Palavra-Chave | Critério de Rateio, Unidade de Saúde |
| Tag | DB, DBAPURASUS, CRITERIORATEIO, UNIDCENTCUST |
| Caminho (URL) |  |
| Data de criação | 22/10/204 |
| Data de revisão | 22/10/2025 |

## Glossário

**Banco de Dados** - é o conjunto de dados integrados que tem por objetivo atender a uma comunidade de usuário. O compartilhamento dos dados tem reflexo nos sistema e precisam ser estruturados seguindo padrões internacionais de arquetetura e de infraestrutura, para que assim possam ser representados por diagramas e em códigos computacionais. Os dados possuem propriedades e modelos específicos, sendo caracterizados como objetos que, quase sempre precisam ser relacionados. Fonte: (Heuser, 2009)

**Dados pessoais sensíveis** - são sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico, quando vinculado a uma pessoa natural.

**Metadado** - é uma forma de reunir elementos para aumentar a compreensão descritiva de um determinado dado. Eles representam dados sobre dados, ou informações sobre outras informações, que dão estrutura à determinada informação isolada.

**Sistema de Apuração de Custo do SUS(ApuraSUS)** - Sistema que possibilita ao gestor o conhecimento sobre o custo total por mês das instituições de saúde e dos seus setores (por exemplo: UTI, centro obstétrico e laboratório), bem como o custo unitário médio dos produtos destes setores (paciente/dia, parto e exames), para que estes possam embasar decisões administrativas e estratégicas no âmbito das instituições de saúde, secretarias de saúde e até mesmo no modelo de gestão federal aplicado à saúde.

**Programa Nacional de Gestão de Custo(PNGC)** - Trata-se de um programa de fomento à cultura de gestão de custos em saúde no SUS, previsto na Portaria nº 55, de 10 de janeiro de 2018.

**Dados** – Sequência de símbolos ou valores, representados em qualquer meio, produzidos como resultado de um processo natural ou artificial.

**Dados Abertos** – dados acessíveis ao público, representados em meio digital, estruturados em formato aberto, processáveis por máquina, referenciados na internet, disponibilizados, sob licença aberta ou sob domínio público que permita sua livre utilização, consumo ou cruzamento, limitando-se a creditar a autoria ou a fonte.

**Dados Acessíveis ao Público** – qualquer dado gerado ou acumulado pelo Governo que não esteja sob sigilo ou sob restrição de acesso nos termos da Lei nº 12.527, de 18 de 4 novembro de 2011.

**Formato Aberto** – formato de arquivo não proprietário, cuja especificação esteja documentada publicamente e seja de livre conhecimento e implementação, livre de patentes ou qualquer outra restrição legal quanto à sua utilização.

**Plano de Dados Abertos** – documento orientador para as ações, com prazos definidos, de implementação e promoção de abertura de dados de cada órgão ou entidade da administração pública federal, obedecidos os padrões mínimos de qualidade, de forma a facilitar o entendimento e a reutilização das informações.

**Governança Digital** – utilização, pelo setor público, de tecnologias da informação e comunicação com o objetivo de melhorar a informação e a prestação de serviços, incentivando a participação dos cidadãos no processo de tomada de decisão e tornando o governo mais responsável, transparente e eficaz.

**Dados Abertos Governamentais** – metodologia para a publicação de dados do governo em formatos reutilizáveis, visando o aumento da transparência e maior participação política por parte do cidadão, além de gerar diversas aplicações desenvolvidas colaborativamente pela sociedade.

**ApuraSUS** -sua principal finalidade é ofertar uma estratégia de qualificação e apoio para entes federados e instituições de saúde na realização da apuração e gestão de custos em saúde de forma padronizada e sistemática.

**Análise de sistema** - é uma das atividades utilizadas de forma estratégica na organização contemporânea. Tem como propósito estudar os processosintenos da instituição e suas interações com o mercado externo, com vista a racionalizar as ações. Com o levantamento de informações, a anális de sistemas permite a adoção de determinados comportamento a fim de melhorar a produtividade e a maneira de atingir o mercado positivamente.

**Dados** – Sequência de símbolos ou valores, representados por qualquer meio, que produz como resultado variáveis. Podem ser criados de forma natural ou artificial e quase sempre precisam ser tratados para realização de análises. São fontes de conhecimento e para tomada de decisão.

**Dados Abertos** – dados acessíveis ao público, representados em meio digital, estruturados em formato aberto, processáveis por máquina, referenciados na internet, disponibilizados, sob licença aberta ou sob domínio público que permita sua livre utilização, consumo ou cruzamento, limitando-se a creditar a autoria ou a fonte.

**Dados Acessíveis ao Público** – qualquer dado gerado ou acumulado pelo Governo que não esteja sob sigilo ou sob restrição de acesso nos termos da Lei nº 12.527, de 18 de 4 novembro de 2011.

**Formato Aberto** – formato de arquivo não proprietário, cuja especificação esteja documentada publicamente e seja de livre conhecimento e implementação, livre de patentes ou qualquer outra restrição legal quanto à sua utilização.

**Plano de Dados Abertos** – documento orientador para as ações, com prazos definidos, de implementação e promoção de abertura de dados de cada órgão ou entidade da administração pública federal, obedecidos os padrões mínimos de qualidade, de forma a facilitar o entendimento e a reutilização das informações.

**Governança Digital** – é a gestão do planejamento, organização, decisão e controle acerca dos processos de governança, tático e operacional. Utilizado pelo setor público com a aplicação de tecnologias da informação e comunicação com o objetivo de melhorar a informação e a prestação de serviços, incentivando a participação dos cidadãos no processo de tomada de decisão e tornando o governo mais responsável, transparente e eficaz.

**Dados Abertos Governamentais** – metodologia para a publicação de dados do governo em formatos reutilizáveis, visando o aumento da transparência e maior participação política por parte do cidadão, além de gerar diversas aplicações desenvolvidas colaborativamente pela sociedade.

**Sistema ApuraSUS** - sua principal finalidade é ofertar uma estratégia de qualificação e apoio para entes federados e instituições de saúde na realização da apuração e gestão de custos em saúde de forma padronizada e sistemática.

**Análise de sistema** - é uma das atividades utilizadas de forma estratégica na organização contemporânea. Tem como propósito estudar os processos internos da instituição e suas interações com o mercado externo, com vista a racionalizar as ações. Com o levantamento de informações, a análise de sistemas permite a adoção de determinados comportamentos a fim de melhorar a produtividade e a maneira de atingir o mercado positivamente.

**Informática** - também chamada ciência da computação, essa área do conhecimento representa o conjunto de estudos desenvolvidos sobre o uso de técnicas, metodologia e instrumentos computacionais. Para além da proposta de automatizar processos manuais, a informática trabalha na modelagem e na transformação da informação, de modo a apresentar os cenários aos usuários de forma compreensível, visando facilitar a atuação dos profissionais no dia a dia da organização.

**Sistema de informação** - decorrente da atividade de análise de sistema, é um conjunto organizado de elementos que interagem segundo regras para que informações sejam processas conforme diferentes visões de usuários em relação aos fatos que ocorrem no cotidiano das organizações do mercado contemporâneo. Os sistemas de informações representam a racionalização da aplicação da tecnologia da informação no interior das organizações.

**Tecnologia da informação** - é uma definição simplificada para tecnologia das informações: ferramental tecnológico aliado a técnica voltadas para atendimento de necessidades que vão desde a criação de infraestrutura, passando por assuntos relativos à segurança da informação, até à governança e ao comércio eletrônico, via implantação de uma série diferenciada de ferramentas.

**Big data** - Jargão da informática utilizado para definir grandes volumes de dados captados pelos motores de busca e armazenados pelas organizações em atividades de *data mining* e *data Warehouse*. Sobre esses grandes repositórios, são realizados diversos tipos de pesquisas de modo a promover a transformação delas em informação útil.

\*\*Computação em nuvem\* - termo essencialmente técnico, que define como a possibilidade por parte das organizações de comercializar software e hardware para que as pessoas não necessitem reservar e nem comprar e instalar aplicativos em seu computador. Elas podem pagar somente pela utilização que fizerem desses produtos: espaços de armazenamento, processamento, licenças e serviços de suporte, de acordo com contratos que podem ser cancelados a qualquer momento.

**Data mining e Data Warehouse** - são respectivamente frameworks de mineração de dados e de armazenamento, são as atividades de pesquisa com utilização dos motores de busca e armazenamento em estado bruto das informações coletadas. Elas suportam a tomada de decisão.

**Sistema de Suporte a Decisão (DSS)** - vem do inglês Decision Support Systems, em que transformam as informações e as apresentam aos usuários de forma que eles possam identificar e resolver problemas de forma ágil e eficaz (na tomada de decisão).

**Informações estruturadas** - para compreender o que representa uma informação estruturada é preciso, em primeiro lugar, saber identificar e definir o que é uma informação não estruturada. Os dados são recolhidos e guardados e depois de organizados, transformam-se em informação não estruturadas. O tratamento desta para que possa responder a determinado contexto lhe dá o caráter de informação estruturada.

**Metadados** - são uma forma de reunir elementos destinados a aumentar a compreensão descritiva de recursos eletrônicos. Eles representam dados sobre os outros dados, ou informações sobre outras informações, que dão estrutura à determinada informação isolada.

**Auditoria de Sistemas** - atividade que examina de forma minuciosa os processos e seus relacionamento na tentativa de entender e confrontar resultados previstos e/ou preestabelecido com o proposto. Podem, também, sugerir ou determinar melhorias aos fluxos processuais.

**Inteligência artificial** - é um dos diversos ramos da ciência da computação com a tarefa precípua de elaborar dispositivos ou programas capazes de simular a capacidade humana de raciocinar, perceber e tomar decisões. Por meio dela surgem conceitos como Aprendizado Máquina (Machine Learning), Rede Neurais e Linguagem Natural que propõem modelos matemáticos e estatísticos capazes de sistematizar e processar sequências lógicas utilizando expressões numéricas em códigos computacionais.

**Aprendizado de Máquina** - do inglês Machine Learning, é a ciência de dados de áreas como a estatística que utiliza conceitos de análise exploratória, probabilidade, inferência, testes estatísticos, que de forma programa alimentam continuamente um modelo de processamento, que o torna capaz de aprender por reforço.

**Redes neurais** - é um método geral e prático para o aprendizado de aproximações de funções a partir de exemplos. Tem sido utilizada com sucesso em muitos problemas, tais como interpretações virtuais de cenas, reconhecimento de escritas, controle de processo e várias outras formas de aprendizado com lógica robotizada.

**Processamento de linguagem natural** - é uma subárea da inteligência artificial na interação entre computadores e a linguagem humana. Em termos simples é a capacidade dos computadores de entender, interpretar e gerar a linguagem que nós, humanos, usamos no dia a dia. Esta habilidade é crucial para uma ampla gama de aplicações, desde assistentes virtuais, chatbots e até tradução automática e análise de sentimento.

**Assistentes virtuais e chat Chatboots** - são formas de inteligência artificial de entender, interpretar e gerar a linguagem humana. Por exemplo: a Siri, Alexa e Google Assistant. Podem entender e responder a comando de voz. Esses assistentes ajudam os usuários a realizar uma variedade de tarefas, desde definir lembretes até controlar dispositivos domésticos inteligentes. O Chatboot, por sua vez são amplamente usados no atendimento ao cliente, proporcionando respostas rápidas e eficientes às consultas dos usuários.

**Sistema de recomendação** - os sistemas de recomendações são substratos da inteligência artificial, visto como forma de classificar ou de regressão para predizer algo com a finalidade de apoiar a tomada de decisão ou de medição de impactos pela confirmação dos fatos prospectados. Criam modelos matemáticos ou estatísticos capazes de aprender com dados retroativos e projetá-los à frente, de forma a fornecer cenários e dar razoável segurança à tomada de decisão.

**Python** - é um sistema de programação de código aberto com linguagem orientada a objeto. Tornou-se uma das linguagens mais populares e utilizada por ser prática e de fácil compreensão. São script criados de forma rápida na automatização de tarefas e para sequência lógica de processos computacionais na automatização.

**R** - é um programa livre e um ambiente computacional de exploração de gráficos e análise de dados. Ele é útil para interpretação de dados, das seguintes maneiras: super-calculadora, ambientes com diversos pacotes estatístico; ferramenta de gráficos de alta qualidade; e linguagem de programação multiuso. O R foi criado por programadores e estatísticos e é mais frequentemente utilizado por analista com conhecimento em álgebra matricial e programação.

**Análise exploratória de dados com Python e R** - as bases de dados podem ser trabalhadas no Python e no R utilizando os conceitos de indexação e subscrição. A indexação pode ser utilizada com operadores (expressões numéricas) para selecionar subconjuntos de um conjunto. A subscrição são vetores que exploram os dados em etapas de processamentos.

**Java** - é uma linguagem de programação computacional orientada a objeto, que é inseparável da linguagem e seu princípio básico de organizar um programa é: por códigos (o que ocorrendo); ou a partir dos seus dados (o que está sendo afetado).

**SQL** - é a tradução para Structured Query Language, do inglês Linguagem de Consulta Estruturada. É uma linguagem de computador com aplicações de se comunicar com várias outras formas. São tabelas que se relacionam com a função de banco de dados. Trata-se da manipulação das tabelas relacionais.

**Epidemiologia** - é o estudo da programação de doenças transmissíveis em populações de indivíduos. Por meio dos modelos matemáticos e epidemiológicos procura-se estudar e analisar o modo de transmissão e a discutir soluções relacionadas a doenças de caráter endêmica. Ela está ligada ao fato de se tentar prever o comportamento de uma epidemia e se antecipar, podendo adotar meios de prevenção.

**Projeto de banco de dados** - o projeto de banco de dados ocorre usualmente em três etapas. A primeira etapa de modelagem conceitual captura formalmente os requisitos de informação de um banco de dados. A segunda é o projeto lógico, que define no nível do Sistema de Governança de Banco de Dados – SGBD, as estruturas de dados que implementarão os requisitos identificados na modelagem conceitual. Já a terceira, o projeto físico, estabelece parâmetros físicos de acesso ao banco de dados, procurando otimizar o desempenho do sistema como um todo. **Administração Pública** - órgão ou entidade integrante da administração pública de qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios, a Advocacia Pública e a Defensoria Pública.

**Ameaça de risco** - causa potencial de um incidente indesejado, que pode comprometer os ativos (como informações, processos e sistemas) e, consequentemente, resultar em dano para as organizações. Ameaças podem ser de origem natural ou humana, podem ser acidentais ou intencionais e podem surgir de dentro ou de fora da organização.

**Ativo patrimonial e da informação** - algo ou característica, tangível ou intangível, que tenha valor para a organização e que, portanto, requeira proteção. São exemplos de ativos: instalações físicas, hardware, software, dados, informações, redes de computadores, processos organizacionais, estrutura organizacional, recursos humanos, serviços utilizados pela organização, imagem da organização, entre outros. Os ativos da informação contemplam sistemas, meios de armazenamento, de transmissão e processamento dos dados, bem como os locais onde se encontram esses meios e as pessoas que a eles têm acesso.

**Público externo** - são cidadãos e cidadãs, sociedade civil, órgãos da União, órgãos de Controles como TCU, CGU, AGU, MPU e da justiça, entes federais, estaduais e municipais, institutos de pesquisas e Universidades, entidades de classes, estados estrangeiros e organismos internacionais como ONU, OMS, OPAS e OCDE.

**Autenticidade dos dados e das informações** - atributos dos dados e das informações que permitem atestar sua proveniência, veracidade e fidedignidade, garantindo que a informação não tenha sofrido mutações ao longo de um processo.

**Autoridade Nacional de Proteção de Dados (ANPD)** - órgão da administração pública responsável por zelar, implementar e fiscalizar o cumprimento desta Lei em todo o território nacional.

**Cobit 5** - o Cobit 5 é um guia de referência para a governança e a gestão da tecnologia da informação e comunicação (TIC) no ambiente corporativo. Ele visa promover a adequação dos investimentos em TIC, garantir a entrega de tais serviços e prover métricas para o acompanhamento do desempenho da governança e da gestão de TIC na organização. O Cobit 5 consolida as boas práticas em um modelo de domínios e processos com as práticas congregadas em uma estrutura lógica e gerenciável. As boas práticas contidas no Cobit representam o consenso de especialistas em governança e gestão de TIC em todo o mundo. **Comitê Gestor de Segurança da Informação (CGSI)** - grupo multidisciplinar que reúne representantes das diversas áreas, indicados pelas suas respectivas autoridades, e aprovados pela alta administração, com o papel de promover e acompanhar as estratégias para implantação e manutenção da análise de riscos, da normatização, de um Sistema de Gestão de Segurança da Informação e das demais iniciativas relativas à segurança da informação. O CGSI foi instituído em conformidade com o art. 6º do Ato da Mesa nº 47, de 16 de julho de 2012, que estabeleceu a Política de Segurança da Informação da Câmara dos Deputados. Suas competências estão definidas no § 3º do art. 6º desse Ato. **Confidencialidade** - atributo que define o grau de sigilo ou de restrição de acesso definido em lei ou atribuído por autoridade competente a um dado, a uma informação ou a um documento.

**Código malicioso** - qualquer programa de computador, ou parte de um programa, construído com a intenção de provocar danos, obter informações não autorizadas ou interromper o funcionamento de sistemas e/ou redes de computadores.

**Consentimento/autorização para uso de dados pessoais ou estratégicos** - ato no qual se manifesta a livre utilização de dados pessoais e estratégicos das organizações, em que de forma inequívoca e formal o titular concorda com o tratamento de seus dados pessoais para uma finalidade determinada.

**Controlador do tratamento de dados** - pessoa natural ou jurídica, de direito público ou privado, a quem competem as decisões referentes ao tratamento de dados pessoais, assim como seu compartilhamento, sendo esse responsável legal, que responde aos ditames da lei por situações controversas e/ou ilícitas.

**Controles de acesso aos bancos de dados** - sistemática cuja função principal é impedir que pessoas acessem documentos, dados ou qualquer tipo de informação sem a autorização adequada.

**Criptografia de dados ou informações de acesso restrito** - conjunto de técnicas fundamentais para a proteção tanto dos dados que estão armazenados em dispositivos eletrônicos, quanto das informações que circulam via internet. O processo de criptografia redefine em fragmentos o conjunto de dados/informações que são transitadas por redes digitais, de forma a dar segurança e integridade a elas. Pode se dar de forma síncrona ou assíncrona e por chaveamento de acesso entre remetente e destinatário.

**Dado anonimizado** - dado relativo ao titular que não possa ser identificado, considerando a utilização de meios técnicos razoáveis e disponíveis na ocasião de seu tratamento. Essa técnica transforma nomes, cpf e outros dados de cunho pessoal em uma linguagem de tradução específica, que impossibilita sua real características.

**Dado pessoal sensível** - dado pessoal ou de uma organização sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico, quando vinculado a uma pessoa natural. São informações que pertencem a um proprietário ou a uma organização, que por questões pessoais ou estratégicas como segurança podem expor seus proprietários.

**Dado pessoal** - informação relacionada a pessoa natural identificada ou não, de caráter único e que a descreve de forma física ou biológica, assim como: origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico, quando vinculado a uma pessoa natural. São informações que pertencem a um proprietário ou a uma organização, que por questões pessoais ou estratégicas como segurança podem expor seus proprietários.

\*\*Declaração de aplicabilidade do dado\* - documento em formato físico ou digital que descreve como serão utilizados os dados e a forma que serão aplicados, a exemplo, pesquisas e estudos, sensos, artigos e outros meios de comunicação com diversos formatos (gráficos, grafos, diagrama, quadros, tabelas, textos, figuras). O usuário que irá manipular os dados precisa declarar como irá aplica-los, as ferramentas de publicação e o conceito desses, para que assim possam passar seu significado na integra.

**Disponibilidade dos dados** - atributo que define que a informação esteja sempre disponível para o uso legítimo, ou seja, por aqueles usuários autorizados pelo proprietário da informação. A disponibilidade é caracterizada na forma de documentação, na qual a organização relaciona quais controles de segurança da informação são recomendadas. Geralmente são aplicados frameworks que auxiliam na construção da estrutura de fornecimento dos dados, como a ANBT/NBR ISO/IEC 27001:2013 que é aplicável aos processos de trabalho e aos ativos de informação. Sugerem controles que compõem o Sistema de Gestão de Segurança da Informação (SGSI).

**Encarregado dos dados** - pessoa indicada pelo controlador dos dados que atua como operador do canal de comunicação entre o controlador, os titulares dos dados e a Autoridade Nacional de Proteção de Dados (ANPD).

**Informação classificada como reservada** - possui prazo máximo de restrição de acesso de 5 (cinco) anos a partir da data de sua produção (art. 24, III, da Lei nº 12.527/2011).

**Informação secreta** - é classificada com prazo máximo de restrição de acesso de 15 (quinze) anos a partir da data de sua produção (art. 24, II, da Lei nº 12.527/2011).

**Informação sigilosa** - é aquela submetida temporariamente a restrição de acesso público em razão de sua imprescindibilidade para a segurança da sociedade e do Estado (art 4º, III, da Lei nº 12.527/2011).

**Informação ultrassecreta** é classificada com prazo máximo de restrição de acesso de 25 (vinte e cinco) anos a partir da data de sua produção (art. 24, I, da Lei nº 12.527/2011).

**Integridade da informação** - é o atributo da informação que se encontra na sua forma original, sem alteração e completa e, que não sofreu nenhum tipo de dano documental ou acidental.

**Núcleo de Ciência de Dados** setor responsáveis pela produção de informações, pelo meio de exploração e de análise dos dados. Segue etapas definidas por frameworks de boas práticas e de aplicação de técnicas científicas nos campos da estatística e matemática, tecnologia da informação e da ciência aplicada. Suas etapas são: demanda ou problema; coleta; limpeza; criação de atributos; normalização; extrair amostras; criação do modelo, treinar e testá-lo, avaliar seu desempenho e, por último, implementá-lo.

**Política de Segurança da Informação** - conjunto adequado de controles, incluindo políticas, processos, procedimentos, estrutura organizacional e funções de software e hardware. Esses controles precisam ser estabelecidos, implementados, monitorados, analisados criticamente e melhorados e, quando necessário, assegurar que os objetivos do negócio e a segurança da informação da organização sejam atendidos.

**Restrição de acesso aos dados** - a Lei de Acesso à Informação prevê os seguintes casos de restrição à informação, tendo como princípio a observância da publicidade como preceito geral e do sigilo como exceção (art 3º, I, da Lei nº 12.527/2011): Quando uma informação for declarada sigilosa pelas autoridades competentes, por ter sido considerada imprescindível à segurança da sociedade e do Estado (art. 24 da Lei nº 12.527/2011). Quando se tratar de informações pessoais, ou seja, aquelas relativas à intimidade, vida privada, honra e imagem de um indivíduo (art. 31 da Lei nº 12.527/2011). Quando as informações forem consideradas de acesso restrito em razão das demais hipóteses legais de sigilo (art. 22 da Lei nº 12.527/2011). As informações pessoais terão seu acesso restrito à própria pessoa, a alguém por ela autorizada ou a agentes públicos legalmente autorizados pelo prazo máximo de 100 (cem) anos a contar da sua data de produção (art. 31 da Lei nº 12.527/2011).

## Referências

[SIOPS](https://bvsms.saude.gov.br/bvs/folder/sistema_informacao_orcamentos_publicos_saude.pdf%20https://www.gov.br/saude/pt-br/acesso-a-informacao/dados-abertos/pda/plano-de-dados-abertos_ms_2024-2026.pdf/view "Infomações sobre o SIOPS")

[ApuraSUS](https://www.gov.br/saude/pt-br/composicao/sectics/desid/apurasus)

[Decreto 8777](https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/D8777.htm "Dados abertos")

[Dados Abertos](https://datasus.saude.gov.br/?s=D%C3%ADcion%C3%A1rio+de+dados "DATASUS - Informações de dados aberto")

[DESID](https://www.gov.br/saude/pt-br/composicao/sectics/desid#:~:text=O%20Departamento%20de%20Economia%20e%20Desenvolvimento%20em%20Sa%C3%BAde,o%20Programa%20Nacional%20de%20Gest%C3%A3o%20de%20Custos%20%28PNGC%29. "Informações sobre o Departamento de Economia e Desenvolvimento em Saúde - DESID")

[RIPSA](https://www.ripsa.org.br/ "Indicadores Básicos para Saúde no Brasil")

[IND](https://www.gov.br/governodigital/pt-br/infraestrutura-nacional-de-dados "Infraestrutura Nacional de Dados")

[Decreto nº 9.903, de 8 de julho de 2019](http://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/decreto/D9903.htm)

[Decreto nº 8.777, de 11 de maio de 2016](http://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/d8777.htm)

[Resolução nº 3 do CGINDA](http://wiki.dados.gov.br/GetFile.aspx?File=%2fComiteGestor%2fResolu%C3%A7%C3%B5es%2fresolucao-cginda)

[Portal Brasileiro de Dados Abertos](http://dados.gov.br/)

[Painel de Monitoramento de Dados Abertos](http://paineis.cgu.gov.br/dadosabertos/index.htm)

[Wiki da Infraestrutura Nacional de Dados Abertos](http://wiki.dados.gov.br/)

[Portal da Transparência](http://www.portaldatransparencia.gov.br/)

[Open Data Institute](https://theodi.org/)

[W3C Brasil](http://www.w3c.br/Home/WebHome)

[Melhores práticas para a publicação de dados na web (recomendação do W3C)](https://www.w3.org/TR/dwbp/)

[Modelo de Maturudade de Dados Aberto - open Data Institute](http://ceweb.br/publicacao/modelo-de-maturidade-de-dados-abertos/)
:::

::: panel-tabset
## Metadado

| Base de Dados (Sistema) | Sistema de Apuração e Gestão de Custos do SUS - ApuraSUS |
|----|----|
| Dado | Tabela AU_TBMAPARELPRODUCAO |
| Descrição | Log da tabela DBAPURASUS.TB_MAPAREL_PRODUCAO: Tabela de |
| Cadastramento dos Centros de Custos para o Mapa de Relacionamento das Produçơes Mensais das Unidades de Saúde; |  |
| Palavra-Chave | Critério de Rateio, Unidade de Saúde, Centros de Custos, Mapa de Relacionamento |
| Tag | DB, DBAPURASUS, CRITERIORATEIO, UNIDCENTCUST |
| Caminho (URL) |  |
| Data de criação | 22/10/204 |
| Data de revisão | 22/10/2025 |

## Glossário

## Referências

[SIOPS](https://bvsms.saude.gov.br/bvs/folder/sistema_informacao_orcamentos_publicos_saude.pdf%20https://www.gov.br/saude/pt-br/acesso-a-informacao/dados-abertos/pda/plano-de-dados-abertos_ms_2024-2026.pdf/view "Infomações sobre o SIOPS")

[Decreto 8777](https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/D8777.htm "Dados abertos")

[Dados Abertos](https://datasus.saude.gov.br/?s=D%C3%ADcion%C3%A1rio+de+dados "DATASUS - Informações de dados aberto")

[DESID](https://www.gov.br/saude/pt-br/composicao/sectics/desid#:~:text=O%20Departamento%20de%20Economia%20e%20Desenvolvimento%20em%20Sa%C3%BAde,o%20Programa%20Nacional%20de%20Gest%C3%A3o%20de%20Custos%20%28PNGC%29. "Informações sobre o Departamento de Economia e Desenvolvimento em Saúde - DESID")

[RIPSA](https://www.ripsa.org.br/ "Indicadores Básicos para Saúde no Brasil")
:::

::: panel-tabset
## Metadado

| Base de Dados (Sistema) | Sistema de Apuração e Gestão de Custos do SUS - ApuraSUS |
|----|----|
| Dado | Tabela RL_CENTROCUSTO_TIPOUNIDADE |
| Descrição | Os Tipos de Unidades para os Centros de Custos (Tabela deverá possuir |

permissăo de deleçăo de dados para os seus usuários - O controle será feito no Log de Segurança da Aplicaçăo) \| \| Palavra-Chave \| Tipos de Unidades, Log de Segurança \| \| Tag \| DB, RL_CENTROCUSTO_TIPOUNIDADE \| \| Caminho (URL) \| \| \| Data de criação \| 22/10/204 \| \| Data de revisão \| 22/10/2025 \|

## Glossário

## Referências

[SIOPS](https://bvsms.saude.gov.br/bvs/folder/sistema_informacao_orcamentos_publicos_saude.pdf%20https://www.gov.br/saude/pt-br/acesso-a-informacao/dados-abertos/pda/plano-de-dados-abertos_ms_2024-2026.pdf/view "Infomações sobre o SIOPS")

[Decreto 8777](https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/D8777.htm "Dados abertos")

[Dados Abertos](https://datasus.saude.gov.br/?s=D%C3%ADcion%C3%A1rio+de+dados "DATASUS - Informações de dados aberto")

[DESID](https://www.gov.br/saude/pt-br/composicao/sectics/desid#:~:text=O%20Departamento%20de%20Economia%20e%20Desenvolvimento%20em%20Sa%C3%BAde,o%20Programa%20Nacional%20de%20Gest%C3%A3o%20de%20Custos%20%28PNGC%29. "Informações sobre o Departamento de Economia e Desenvolvimento em Saúde - DESID")

[RIPSA](https://www.ripsa.org.br/ "Indicadores Básicos para Saúde no Brasil")
:::

::: panel-tabset
## Metadados

| Base de Dados (Sistema) | Sistema de Apuração e Gestão de Custos do SUS - ApuraSUS |
|----|----|
| Dado | Tabela RL_CRITERIORATEIO_UNIDCENTCUST |
| Descrição | Tabela de Relaçăo dos Critério de Rateios para a Unidade de Saúde |
| Palavra-Chave | Relaçăo dos Critério de Rateios, Unidade de Saúde |
| Tag | DBAPURASUS |
| Caminho (URL) |  |
| Data de criação | 22/10/204 |
| Data de revisão | 22/10/2025 |

## Glossário

## Referências

[SIOPS](https://bvsms.saude.gov.br/bvs/folder/sistema_informacao_orcamentos_publicos_saude.pdf%20https://www.gov.br/saude/pt-br/acesso-a-informacao/dados-abertos/pda/plano-de-dados-abertos_ms_2024-2026.pdf/view "Infomações sobre o SIOPS")

[Decreto 8777](https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/D8777.htm "Dados abertos")

[Dados Abertos](https://datasus.saude.gov.br/?s=D%C3%ADcion%C3%A1rio+de+dados "DATASUS - Informações de dados aberto")

[DESID](https://www.gov.br/saude/pt-br/composicao/sectics/desid#:~:text=O%20Departamento%20de%20Economia%20e%20Desenvolvimento%20em%20Sa%C3%BAde,o%20Programa%20Nacional%20de%20Gest%C3%A3o%20de%20Custos%20%28PNGC%29. "Informações sobre o Departamento de Economia e Desenvolvimento em Saúde - DESID")

[RIPSA](https://www.ripsa.org.br/ "Indicadores Básicos para Saúde no Brasil")
:::

::: panel-tabset
## Metadados

| Base de Dados (Sistema) | Banco de Preço em Saúde - BPS |
|----|----|
| Dado | Table tb_classe |
| Descrição | Tabela que contém os registros de Classes disponíveis |
| Palavra-Chave | Código sequencial, classe, registro |
| Tag | bigint, integer, varchar, indexes |
| Caminho (URL) |  |
| Data de criação | 22/10/2024 |
| Data de revisão | 22/10/2025 |

## Glossário

## Referências

[SIOPS](https://bvsms.saude.gov.br/bvs/folder/sistema_informacao_orcamentos_publicos_saude.pdf%20https://www.gov.br/saude/pt-br/acesso-a-informacao/dados-abertos/pda/plano-de-dados-abertos_ms_2024-2026.pdf/view "Infomações sobre o SIOPS")

[Decreto 8777](https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/D8777.htm "Dados abertos")

[Dados Abertos](https://datasus.saude.gov.br/?s=D%C3%ADcion%C3%A1rio+de+dados "DATASUS - Informações de dados aberto")

[DESID](https://www.gov.br/saude/pt-br/composicao/sectics/desid#:~:text=O%20Departamento%20de%20Economia%20e%20Desenvolvimento%20em%20Sa%C3%BAde,o%20Programa%20Nacional%20de%20Gest%C3%A3o%20de%20Custos%20%28PNGC%29. "Informações sobre o Departamento de Economia e Desenvolvimento em Saúde - DESID")

[RIPSA](https://www.ripsa.org.br/ "Indicadores Básicos para Saúde no Brasil")
:::

::: panel-tabset
## Metadados

| Base de Dados (Sistema) | Banco de Preço em Saúde - BPS |
|----|----|
| Dado | Table tb_grupo |
| Descrição | Tabela que contém os registros de Grupos disponíveis |
| Palavra-Chave | Código sequencial, classe, registro |
| Tag | bigint, integer, varchar, indexes |
| Caminho (URL) |  |
| Data de criação | 22/10/2024 |
| Data de revisão | 22/10/2025 |

## Glossário

## Referências

[SIOPS](https://bvsms.saude.gov.br/bvs/folder/sistema_informacao_orcamentos_publicos_saude.pdf%20https://www.gov.br/saude/pt-br/acesso-a-informacao/dados-abertos/pda/plano-de-dados-abertos_ms_2024-2026.pdf/view "Infomações sobre o SIOPS")

[Decreto 8777](https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/D8777.htm "Dados abertos")

[Dados Abertos](https://datasus.saude.gov.br/?s=D%C3%ADcion%C3%A1rio+de+dados "DATASUS - Informações de dados aberto")

[DESID](https://www.gov.br/saude/pt-br/composicao/sectics/desid#:~:text=O%20Departamento%20de%20Economia%20e%20Desenvolvimento%20em%20Sa%C3%BAde,o%20Programa%20Nacional%20de%20Gest%C3%A3o%20de%20Custos%20%28PNGC%29. "Informações sobre o Departamento de Economia e Desenvolvimento em Saúde - DESID")

[RIPSA](https://www.ripsa.org.br/ "Indicadores Básicos para Saúde no Brasil")
:::

::: panel-tabset
## Metadados

| Base de Dados (Sistema) | Banco de Preço em Saúde - BPS |
|----|----|
| Dado | Table tb_grupo |
| Descrição | Tabela que contém os registros de Grupos disponíveis |
| Palavra-Chave | Código sequencial, classe, registro |
| Tag | bigint, integer, varchar, indexes |
| Caminho (URL) |  |
| Data de criação | 22/10/2024 |
| Data de revisão | 22/10/2025 |

## Glossário

## Referências

[SIOPS](https://bvsms.saude.gov.br/bvs/folder/sistema_informacao_orcamentos_publicos_saude.pdf%20https://www.gov.br/saude/pt-br/acesso-a-informacao/dados-abertos/pda/plano-de-dados-abertos_ms_2024-2026.pdf/view "Infomações sobre o SIOPS")

[Decreto 8777](https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/D8777.htm "Dados abertos")

[Dados Abertos](https://datasus.saude.gov.br/?s=D%C3%ADcion%C3%A1rio+de+dados "DATASUS - Informações de dados aberto")

[DESID](https://www.gov.br/saude/pt-br/composicao/sectics/desid#:~:text=O%20Departamento%20de%20Economia%20e%20Desenvolvimento%20em%20Sa%C3%BAde,o%20Programa%20Nacional%20de%20Gest%C3%A3o%20de%20Custos%20%28PNGC%29. "Informações sobre o Departamento de Economia e Desenvolvimento em Saúde - DESID")

[RIPSA](https://www.ripsa.org.br/ "Indicadores Básicos para Saúde no Brasil")
:::

::: panel-tabset
## Metadados

| Base de Dados (Sistema) | Banco de Preço em Saúde - BPS |
|----|----|
| Dado | Table tb_revisao |
| Descrição | Tabela que contém os registros de Classes disponíveis |
| Palavra-Chave | Código sequencial, classe, registro |
| Tag | bigint, integer, varchar, indexes |
| Caminho (URL) |  |
| Data de criação | 22/10/2024 |
| Data de revisão | 22/10/2025 |

## Glossário

## Referências

[SIOPS](https://bvsms.saude.gov.br/bvs/folder/sistema_informacao_orcamentos_publicos_saude.pdf%20https://www.gov.br/saude/pt-br/acesso-a-informacao/dados-abertos/pda/plano-de-dados-abertos_ms_2024-2026.pdf/view "Infomações sobre o SIOPS")

[Decreto 8777](https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/D8777.htm "Dados abertos")

[Dados Abertos](https://datasus.saude.gov.br/?s=D%C3%ADcion%C3%A1rio+de+dados "DATASUS - Informações de dados aberto")

[DESID](https://www.gov.br/saude/pt-br/composicao/sectics/desid#:~:text=O%20Departamento%20de%20Economia%20e%20Desenvolvimento%20em%20Sa%C3%BAde,o%20Programa%20Nacional%20de%20Gest%C3%A3o%20de%20Custos%20%28PNGC%29. "Informações sobre o Departamento de Economia e Desenvolvimento em Saúde - DESID")

[RIPSA](https://www.ripsa.org.br/ "Indicadores Básicos para Saúde no Brasil")
:::

::: panel-tabset
## Metadados

| Base de Dados (Sistema) | Sistema de Informações sobre Orçamentos Públicos em Saúde - SIOPS |
|----|----|
| Dado | SIOPS-DELPHI_CLIENTE_EUC_018_Gerar_Relatorio_Despesa_Saude_Executada_Consorcio_Publico.docx |
| Descrição | Este caso de uso tem como objetivo especificar a funcionalidade de gerar Relatório de Despesa com Saúde Executada em Consórcio Público para os entes Estadual, Municipal e Distrito Federal do Módulo Cliente 2018 |
| Palavra-Chave | CLIENTE_EUC_018, Despesa. Executada |
| Tag |  |
| Caminho (URL) |  |
| Data de criação | 22/10/2024 |
| Data de revisão | 22/10/2025 |

## Glossário

## Referências

[SIOPS](https://bvsms.saude.gov.br/bvs/folder/sistema_informacao_orcamentos_publicos_saude.pdf%20https://www.gov.br/saude/pt-br/acesso-a-informacao/dados-abertos/pda/plano-de-dados-abertos_ms_2024-2026.pdf/view "Infomações sobre o SIOPS")

[Decreto 8777](https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/D8777.htm "Dados abertos")

[Dados Abertos](https://datasus.saude.gov.br/?s=D%C3%ADcion%C3%A1rio+de+dados "DATASUS - Informações de dados aberto")

[DESID](https://www.gov.br/saude/pt-br/composicao/sectics/desid#:~:text=O%20Departamento%20de%20Economia%20e%20Desenvolvimento%20em%20Sa%C3%BAde,o%20Programa%20Nacional%20de%20Gest%C3%A3o%20de%20Custos%20%28PNGC%29. "Informações sobre o Departamento de Economia e Desenvolvimento em Saúde - DESID")

[RIPSA](https://www.ripsa.org.br/ "Indicadores Básicos para Saúde no Brasil")
:::

::: panel-tabset
## Metadados

| Base de Dados (Sistema) | Sistema de Informações sobre Orçamentos Públicos em Saúde - SIOPS |
|----|----|
| Dado | SIOPS DELPHI_CLIENTE_EUC_009_Gerar_Relatorio_Receita_Orcamentaria.docx |
| Descrição | Este caso de uso tem como objetivo especificar a funcionalidade de Gerar Relatório da Receita Orçamentária para os entes Estadual, Municipal e Distrito Federal do Módulo Cliente 2018 |
| Palavra-Chave | CLIENTE_EUC_009, Relatório, Receita |
| Tag |  |
| Caminho (URL) |  |
| Data de criação | 22/10/2024 |
| Data de revisão | 22/10/2025 |

## Glossário

## Referências

[SIOPS](https://bvsms.saude.gov.br/bvs/folder/sistema_informacao_orcamentos_publicos_saude.pdf%20https://www.gov.br/saude/pt-br/acesso-a-informacao/dados-abertos/pda/plano-de-dados-abertos_ms_2024-2026.pdf/view "Infomações sobre o SIOPS")

[Decreto 8777](https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2016/decreto/D8777.htm "Dados abertos")

[Dados Abertos](https://datasus.saude.gov.br/?s=D%C3%ADcion%C3%A1rio+de+dados "DATASUS - Informações de dados aberto")

[DESID](https://www.gov.br/saude/pt-br/composicao/sectics/desid#:~:text=O%20Departamento%20de%20Economia%20e%20Desenvolvimento%20em%20Sa%C3%BAde,o%20Programa%20Nacional%20de%20Gest%C3%A3o%20de%20Custos%20%28PNGC%29. "Informações sobre o Departamento de Economia e Desenvolvimento em Saúde - DESID")

[RIPSA](https://www.ripsa.org.br/ "Indicadores Básicos para Saúde no Brasil")
:::

::::::::::::::

------------------------------------------------------------------------

## 
